export type Item = {
  order: number;
  slug: string;
  title: string;
  titleEn?: string;
  source: string;
  sourceEn?: string;
  subgroup?: string;
  description?: string;
  descriptionEn?: string;
};

export type Section = {
  id: string;
  title: string;
  titleEn?: string;
  intro?: string;
  introEn?: string;
  items: Item[];
};

export const NAV: Section[] = [
  {
    id: 'get-started',
    title: '快速上手',
    titleEn: 'Get Started',
    intro: '安裝 CLI，5 分鐘內發出第一個路由決策。',
    introEn: 'Install the CLI and make your first routing decision in 5 minutes.',
    items: [
      { order: 101, slug: 'getting-started',
        title: 'Getting Started', titleEn: 'Getting Started',
        source: 'docs/getting-started.md', sourceEn: 'docs/getting-started-en.md',
        description: 'npx gstack-plus classify "..." — 5 分鐘上手',
        descriptionEn: 'Install CLI, make your first routing decision in 5 minutes' },
      { order: 102, slug: 'cli',
        title: 'CLI 使用手冊', titleEn: 'CLI Reference',
        source: 'cli/README.md', sourceEn: 'cli/README-en.md',
        description: 'classify / examples / stats / open / config — 完整命令說明',
        descriptionEn: 'classify / examples / stats / open / config — full command reference' },
      { order: 103, slug: 'changelog',
        title: 'Changelog', titleEn: 'Changelog',
        source: 'CHANGELOG.md', sourceEn: 'CHANGELOG.md' },
    ],
  },
  {
    id: 'framework',
    title: '框架理念',
    titleEn: 'The Framework',
    intro: '三層模型的設計邏輯，以及從實踐中提煉的核心洞察。',
    introEn: 'The design logic behind 3-tier routing and key insights from practice.',
    items: [
      { order: 201, slug: 'architecture',
        title: '三層架構設計', titleEn: '3-Tier Architecture',
        source: 'docs/architecture.md', sourceEn: 'docs/architecture-en.md',
        description: 'Tier-A / Tier-Mid / Tier-Exec 的角色、邊界與成本權衡',
        descriptionEn: 'Roles, boundaries, and cost tradeoffs of the 3-tier model' },
      { order: 202, slug: 'key-insights',
        title: '核心設計洞察', titleEn: 'Key Design Insights',
        source: 'docs/learning-notes/key-insights.md', sourceEn: 'docs/learning-notes/key-insights-en.md',
        description: 'AI 紀律、角色化設計、隔離即品質等 5 個設計原則',
        descriptionEn: '5 design principles from practice: AI discipline, role-based design, isolation-as-quality' },
      { order: 203, slug: 'strategy',
        title: '為什麼要分層？', titleEn: 'Why Layered Routing?',
        source: 'docs/strategy.md', sourceEn: 'docs/strategy-en.md',
        description: 'gstack-plus 的設計動機 — 路由懶惰比模型貴更致命',
        descriptionEn: 'The design motivation — lazy routing is worse than expensive models' },
      { order: 204, slug: 'superpowers-integration',
        title: 'Superpowers 整合', titleEn: 'Superpowers Integration',
        source: 'docs/superpowers-integration.md', sourceEn: 'docs/superpowers-integration-en.md',
        description: '如何將 gstack-plus 與 superpowers 工作流結合',
        descriptionEn: 'How to combine gstack-plus with superpowers workflows' },
    ],
  },
  {
    id: 'classify',
    title: '任務分類',
    titleEn: 'Classify & Route',
    intro: '5 維度評分 + 路由規則 + 20+ 真實任務示範。',
    introEn: '5-dimension scoring + routing rules + 20+ worked task examples.',
    items: [
      { order: 301, slug: 'scoring-guide',
        title: '評分指南', titleEn: 'Scoring Guide',
        source: 'classifier/scoring-guide.md', sourceEn: 'classifier/scoring-guide-en.md',
        description: '5 個維度（判斷、上下文、風險、可驗證、創意）的 1–5 分標準',
        descriptionEn: '1–5 scoring standards for the 5 dimensions' },
      { order: 302, slug: 'routing-rules',
        title: '路由規則', titleEn: 'Routing Rules',
        source: 'classifier/routing-rules.md', sourceEn: 'classifier/routing-rules-en.md',
        description: '從評分到 Tier 的決策表與保守路由原則',
        descriptionEn: 'Decision table from scoring to Tier + conservative routing principle' },
      { order: 303, slug: 'test-tasks',
        title: '20+ 任務評分示範', titleEn: '20+ Worked Tasks',
        source: 'classifier/test-tasks.md', sourceEn: 'classifier/test-tasks-en.md',
        description: '真實任務的分類示範與邊界案例',
        descriptionEn: '20+ real tasks scored across all 5 dimensions with routing decisions' },
    ],
  },
  {
    id: 'handoff',
    title: '交接規範',
    titleEn: 'Handoff & Guardrails',
    intro: 'Tier 之間的信息傳遞格式，以及防止失敗的前置檢查。',
    introEn: 'Structured handoff formats between tiers, plus failure prevention guardrails.',
    items: [
      { order: 401, slug: 'plan-to-exec',
        title: 'Plan → Exec', titleEn: 'Plan → Exec',
        source: 'handoff/templates/plan-to-exec.md', sourceEn: 'handoff/templates/plan-to-exec-en.md',
        subgroup: 'Templates',
        description: 'Tier-A 給 Tier-Exec 的可執行計劃格式',
        descriptionEn: 'Structured handoff format from Tier-A to Tier-Exec' },
      { order: 402, slug: 'exec-to-check',
        title: 'Exec → Check', titleEn: 'Exec → Check',
        source: 'handoff/templates/exec-to-check.md', sourceEn: 'handoff/templates/exec-to-check-en.md',
        subgroup: 'Templates',
        description: 'Tier-Exec 完成後的 evidence 回報格式',
        descriptionEn: 'Evidence report format from Tier-Exec back to Tier-Mid for verification' },
      { order: 403, slug: 'check-to-plan',
        title: 'Check → Plan', titleEn: 'Check → Plan',
        source: 'handoff/templates/check-to-plan.md', sourceEn: 'handoff/templates/check-to-plan-en.md',
        subgroup: 'Templates',
        description: 'Tier-Mid 驗收結果回流給 Tier-A 的格式',
        descriptionEn: 'Result feedback format from Tier-Mid back to Tier-A after verification' },
      { order: 404, slug: 'evidence-format',
        title: 'Evidence 格式', titleEn: 'Evidence Format',
        source: 'handoff/templates/shared/evidence-format.md', sourceEn: 'handoff/templates/shared/evidence-format-en.md',
        subgroup: 'Templates',
        description: '所有「完成宣稱」必備的證據結構',
        descriptionEn: 'Required evidence structure for all completion claims' },
      { order: 405, slug: 'forbidden-words',
        title: '禁用詞表', titleEn: 'Forbidden Words',
        source: 'handoff/templates/shared/forbidden-words.md', sourceEn: 'handoff/templates/shared/forbidden-words-en.md',
        subgroup: 'Templates',
        description: '「適當的、合理的、如果需要」等禁止用詞',
        descriptionEn: 'Banned phrases: "appropriate", "reasonable", "if needed" and similar vague terms' },
      { order: 411, slug: 'pre-flight',
        title: '起飛前檢查清單', titleEn: 'Pre-flight Checklist',
        source: 'verification/pre-flight-checklist.md', sourceEn: 'verification/pre-flight-checklist-en.md',
        subgroup: 'Guardrails',
        description: '12 項交接前必過的檢查（任務清晰 + Tier + 失敗處理）',
        descriptionEn: '12 checks before any handoff — task clarity, tier selection, and failure handling' },
      { order: 412, slug: 'failure-catalog',
        title: '失敗類型目錄', titleEn: 'Failure Catalog',
        source: 'verification/failure-catalog.md', sourceEn: 'verification/failure-catalog-en.md',
        subgroup: 'Guardrails',
        description: 'BUILD_ERROR / LOGIC_ERROR / DESIGN_ISSUE / SCOPE_DRIFT',
        descriptionEn: 'Four failure types with diagnosis signals and recovery paths' },
      { order: 413, slug: 'failure-routing',
        title: '失敗路由規則', titleEn: 'Failure Routing',
        source: 'verification/failure-routing.md', sourceEn: 'verification/failure-routing-en.md',
        subgroup: 'Guardrails',
        description: '從失敗類型到 retry / 升級 / 回流 Tier-A 的決策樹',
        descriptionEn: 'Decision tree from failure type to retry / escalate / return to Tier-A' },
    ],
  },
  {
    id: 'examples',
    title: '完整範例',
    titleEn: 'Examples',
    intro: '5 個真實任務的完整評分過程，看別人怎麼用。',
    introEn: '5 real tasks fully scored — see how routing decisions are made.',
    items: [
      { order: 501, slug: 'ex-tier-exec-eslint',
        title: 'Tier-Exec：加 ESLint 配置', titleEn: 'Tier-Exec: ESLint Config',
        source: 'examples/01-tier-exec-eslint.md', sourceEn: 'examples/01-tier-exec-eslint-en.md',
        subgroup: 'Tier-Exec',
        description: '機械配置任務的典型路由',
        descriptionEn: 'Canonical example of a mechanical config task routed to Tier-Exec' },
      { order: 502, slug: 'ex-tier-exec-rename',
        title: 'Tier-Exec：跨檔案重命名', titleEn: 'Tier-Exec: Cross-file Rename',
        source: 'examples/02-tier-exec-rename.md', sourceEn: 'examples/02-tier-exec-rename-en.md',
        subgroup: 'Tier-Exec',
        description: '上下文寬但判斷低 → 仍可派 Exec',
        descriptionEn: 'High context width but low judgment — still routes to Tier-Exec' },
      { order: 503, slug: 'ex-tier-mid-refactor',
        title: 'Tier-Mid：CQRS 重構', titleEn: 'Tier-Mid: CQRS Refactor',
        source: 'examples/03-tier-mid-refactor.md', sourceEn: 'examples/03-tier-mid-refactor-en.md',
        subgroup: 'Tier-Mid',
        description: '中等判斷 + 中等風險的典型',
        descriptionEn: 'Mid-level judgment and risk — canonical Tier-Mid routing' },
      { order: 504, slug: 'ex-tier-a-auth',
        title: 'Tier-A：設計 SSO + MFA', titleEn: 'Tier-A: SSO + MFA Design',
        source: 'examples/04-tier-a-auth-design.md', sourceEn: 'examples/04-tier-a-auth-design-en.md',
        subgroup: 'Tier-A',
        description: '三個條件同時觸發 Tier-A',
        descriptionEn: 'Three conditions simultaneously trigger Tier-A: high judgment, risk, and creativity' },
      { order: 505, slug: 'ex-borderline',
        title: '邊界案例：cursor pagination', titleEn: 'Borderline: Cursor Pagination',
        source: 'examples/05-borderline-case.md', sourceEn: 'examples/05-borderline-case-en.md',
        subgroup: 'Borderline',
        description: '保守路由原則的應用時機',
        descriptionEn: 'When to apply the conservative routing principle on ambiguous tasks' },
    ],
  },
  {
    id: 'notes',
    title: '學習筆記',
    titleEn: 'Research Notes',
    intro: '深入解剖 gstack 和 superpowers 工作流框架的學習筆記。',
    introEn: 'Deep-dive anatomy notes on the gstack and superpowers workflow frameworks.',
    items: [
      { order: 601, slug: 'notes-index',
        title: '筆記索引', titleEn: 'Notes Index',
        source: 'docs/learning-notes/README.md', sourceEn: 'docs/learning-notes/README-en.md',
        description: '所有學習筆記的入口與閱讀建議',
        descriptionEn: 'Entry point for all learning notes with reading recommendations' },
      { order: 602, slug: 'gstack-overview',
        title: 'gstack 概覽', titleEn: 'gstack Overview',
        source: 'docs/learning-notes/gstack-overview.md', sourceEn: 'docs/learning-notes/gstack-overview-en.md',
        description: 'gstack 框架核心概念與角色體系總覽',
        descriptionEn: 'Core concepts of the gstack framework and role system' },
      { order: 603, slug: 'gstack-anatomy',
        title: 'gstack 解剖', titleEn: 'gstack Anatomy',
        source: 'docs/learning-notes/gstack-anatomy.md', sourceEn: 'docs/learning-notes/gstack-anatomy-en.md',
        description: 'gstack 目錄結構、slots、技能載入機制',
        descriptionEn: 'Directory structure, slots, and skill loading mechanism' },
      { order: 604, slug: 'gstack-planning',
        title: 'gstack 規劃技能', titleEn: 'gstack Planning Skills',
        source: 'docs/learning-notes/gstack-planning-skills.md', sourceEn: 'docs/learning-notes/gstack-planning-skills-en.md',
        description: '規劃類技能（Plan/Review/Ship）的使用模式',
        descriptionEn: 'Usage patterns for planning skills (Plan/Review/Ship)' },
      { order: 605, slug: 'gstack-review',
        title: 'gstack 審查技能', titleEn: 'gstack Review Skills',
        source: 'docs/learning-notes/gstack-review-skills.md', sourceEn: 'docs/learning-notes/gstack-review-skills-en.md',
        description: '審查技能的觸發條件與輸出格式',
        descriptionEn: 'Trigger conditions and output formats for review skills' },
      { order: 606, slug: 'gstack-shipping',
        title: 'gstack 交付技能', titleEn: 'gstack Shipping Skills',
        source: 'docs/learning-notes/gstack-shipping-skills.md', sourceEn: 'docs/learning-notes/gstack-shipping-skills-en.md',
        description: '交付流程技能與 evidence 生成',
        descriptionEn: 'Delivery workflow skills and evidence generation' },
      { order: 607, slug: 'gstack-vs-superpowers',
        title: 'gstack vs superpowers', titleEn: 'gstack vs superpowers',
        source: 'docs/learning-notes/gstack-vs-superpowers.md', sourceEn: 'docs/learning-notes/gstack-vs-superpowers-en.md',
        description: '兩個框架的設計哲學差異與互補關係',
        descriptionEn: 'Design philosophy differences and complementarity between the two frameworks' },
      { order: 608, slug: 'superpowers-anatomy',
        title: 'superpowers 解剖', titleEn: 'superpowers Anatomy',
        source: 'docs/learning-notes/superpowers-anatomy.md', sourceEn: 'docs/learning-notes/superpowers-anatomy-en.md',
        description: 'superpowers 框架目錄結構與技能發現機制',
        descriptionEn: 'Directory structure and skill discovery mechanism of superpowers' },
      { order: 609, slug: 'superpowers-planning',
        title: 'superpowers 規劃', titleEn: 'superpowers Planning',
        source: 'docs/learning-notes/superpowers-planning.md', sourceEn: 'docs/learning-notes/superpowers-planning-en.md',
        description: 'superpowers 規劃技能的結構與觸發模式',
        descriptionEn: 'Structure and trigger patterns for superpowers planning skills' },
      { order: 610, slug: 'superpowers-parallel',
        title: 'superpowers 並行', titleEn: 'superpowers Parallel',
        source: 'docs/learning-notes/superpowers-parallel.md', sourceEn: 'docs/learning-notes/superpowers-parallel-en.md',
        description: 'superpowers 並行任務模型與 Agent 分工',
        descriptionEn: 'Parallel task model and agent division of labor' },
      { order: 611, slug: 'superpowers-quality',
        title: 'superpowers 品質', titleEn: 'superpowers Quality',
        source: 'docs/learning-notes/superpowers-quality.md', sourceEn: 'docs/learning-notes/superpowers-quality-en.md',
        description: 'superpowers 質量控制機制與 review 循環',
        descriptionEn: 'Quality control mechanisms and review cycles' },
    ],
  },
  {
    id: 'research',
    title: '實驗報告',
    titleEn: 'Experiment Reports',
    intro: '對 gstack-plus 方法論的量化驗證：成本、質量、路由穩定性。',
    introEn: 'Quantified validation of the gstack-plus methodology: cost, quality, routing stability.',
    items: [
      { order: 701, slug: 'experiment-series-2',
        title: '實驗 Series 2：多維度有效性驗證',
        titleEn: 'Experiment Series 2: Multi-dimensional Validity',
        source: 'docs/experiment-series-2.md',
        sourceEn: 'docs/experiment-series-2-en.md',
        description: '30 任務路由穩定性 + 9 任務成本對比 + LLM-as-Judge 盲評，三個實驗驗證方法論有效性',
        descriptionEn: '30-task routing stability + 9-task cost benchmark + LLM-as-Judge blind eval — three experiments validate the methodology' },
      { order: 702, slug: 'experiment-series-3',
        title: '實驗 Series 3：Prompt 優化 × 真實語料庫',
        titleEn: 'Experiment Series 3: Prompt Optimization × Real-World Corpus',
        source: 'docs/experiment-series-3.md',
        sourceEn: 'docs/experiment-series-3-en.md',
        description: '4 種 Prompt 策略讓 Sonnet 反超 Opus（15.0 vs 12.7/15，省 86% 成本）+ 20 個真實任務路由 100% 準確',
        descriptionEn: 'S1 prompt strategy lets Sonnet beat Opus (15.0 vs 12.7/15, 86% cost saving) + 100% routing accuracy on 20 real tasks' },
    ],
  },
];
