export type Item = {
  order: number;
  slug: string;
  title: string;
  titleEn?: string;
  source: string;
  subgroup?: string;
  description?: string;
};

export type Section = {
  id: string;
  title: string;
  titleEn?: string;
  intro?: string;
  introEn?: string;
  items: Item[];
};

export const NAV: Section[] = [
  {
    id: 'get-started',
    title: '快速上手',
    titleEn: 'Get Started',
    intro: '安裝 CLI，5 分鐘內發出第一個路由決策。',
    introEn: 'Install the CLI and make your first routing decision in 5 minutes.',
    items: [
      { order: 101, slug: 'getting-started',
        title: 'Getting Started', titleEn: 'Getting Started',
        source: 'docs/getting-started.md',
        description: 'npx gstack-plus classify "..." — 5 分鐘上手' },
      { order: 102, slug: 'cli',
        title: 'CLI 使用手冊', titleEn: 'CLI Reference',
        source: 'cli/README.md',
        description: 'classify / examples / stats / open / config — 完整命令說明' },
      { order: 103, slug: 'changelog',
        title: 'Changelog', titleEn: 'Changelog',
        source: 'CHANGELOG.md' },
    ],
  },
  {
    id: 'framework',
    title: '框架理念',
    titleEn: 'The Framework',
    intro: '三層模型的設計邏輯，以及從實踐中提煉的核心洞察。',
    introEn: 'The design logic behind 3-tier routing and key insights from practice.',
    items: [
      { order: 201, slug: 'architecture',
        title: '三層架構設計', titleEn: '3-Tier Architecture',
        source: 'docs/architecture.md',
        description: 'Tier-A / Tier-Mid / Tier-Exec 的角色、邊界與成本權衡' },
      { order: 202, slug: 'key-insights',
        title: '核心設計洞察', titleEn: 'Key Design Insights',
        source: 'docs/learning-notes/key-insights.md',
        description: 'AI 紀律、角色化設計、隔離即品質等 5 個設計原則' },
    ],
  },
  {
    id: 'classify',
    title: '任務分類',
    titleEn: 'Classify & Route',
    intro: '5 維度評分 + 路由規則 + 20+ 真實任務示範。',
    introEn: '5-dimension scoring + routing rules + 20+ worked task examples.',
    items: [
      { order: 301, slug: 'scoring-guide',
        title: '評分指南', titleEn: 'Scoring Guide',
        source: 'classifier/scoring-guide.md',
        description: '5 個維度（判斷、上下文、風險、可驗證、創意）的 1–5 分標準' },
      { order: 302, slug: 'routing-rules',
        title: '路由規則', titleEn: 'Routing Rules',
        source: 'classifier/routing-rules.md',
        description: '從評分到 Tier 的決策表與保守路由原則' },
      { order: 303, slug: 'test-tasks',
        title: '20+ 任務評分示範', titleEn: '20+ Worked Tasks',
        source: 'classifier/test-tasks.md',
        description: '真實任務的分類示範與邊界案例' },
    ],
  },
  {
    id: 'handoff',
    title: '交接規範',
    titleEn: 'Handoff & Guardrails',
    intro: 'Tier 之間的信息傳遞格式，以及防止失敗的前置檢查。',
    introEn: 'Structured handoff formats between tiers, plus failure prevention guardrails.',
    items: [
      { order: 401, slug: 'plan-to-exec',
        title: 'Plan → Exec', titleEn: 'Plan → Exec',
        source: 'handoff/templates/plan-to-exec.md',
        subgroup: 'Templates',
        description: 'Tier-A 給 Tier-Exec 的可執行計劃格式' },
      { order: 402, slug: 'exec-to-check',
        title: 'Exec → Check', titleEn: 'Exec → Check',
        source: 'handoff/templates/exec-to-check.md',
        subgroup: 'Templates',
        description: 'Tier-Exec 完成後的 evidence 回報格式' },
      { order: 403, slug: 'check-to-plan',
        title: 'Check → Plan', titleEn: 'Check → Plan',
        source: 'handoff/templates/check-to-plan.md',
        subgroup: 'Templates',
        description: 'Tier-Mid 驗收結果回流給 Tier-A 的格式' },
      { order: 404, slug: 'evidence-format',
        title: 'Evidence 格式', titleEn: 'Evidence Format',
        source: 'handoff/templates/shared/evidence-format.md',
        subgroup: 'Templates',
        description: '所有「完成宣稱」必備的證據結構' },
      { order: 405, slug: 'forbidden-words',
        title: '禁用詞表', titleEn: 'Forbidden Words',
        source: 'handoff/templates/shared/forbidden-words.md',
        subgroup: 'Templates',
        description: '「適當的、合理的、如果需要」等禁止用詞' },
      { order: 411, slug: 'pre-flight',
        title: '起飛前檢查清單', titleEn: 'Pre-flight Checklist',
        source: 'verification/pre-flight-checklist.md',
        subgroup: 'Guardrails',
        description: '12 項交接前必過的檢查（任務清晰 + Tier + 失敗處理）' },
      { order: 412, slug: 'failure-catalog',
        title: '失敗類型目錄', titleEn: 'Failure Catalog',
        source: 'verification/failure-catalog.md',
        subgroup: 'Guardrails',
        description: 'BUILD_ERROR / LOGIC_ERROR / DESIGN_ISSUE / SCOPE_DRIFT' },
      { order: 413, slug: 'failure-routing',
        title: '失敗路由規則', titleEn: 'Failure Routing',
        source: 'verification/failure-routing.md',
        subgroup: 'Guardrails',
        description: '從失敗類型到 retry / 升級 / 回流 Tier-A 的決策樹' },
    ],
  },
  {
    id: 'examples',
    title: '完整範例',
    titleEn: 'Examples',
    intro: '5 個真實任務的完整評分過程，看別人怎麼用。',
    introEn: '5 real tasks fully scored — see how routing decisions are made.',
    items: [
      { order: 501, slug: 'ex-tier-exec-eslint',
        title: 'Tier-Exec：加 ESLint 配置', titleEn: 'Tier-Exec: ESLint Config',
        source: 'examples/01-tier-exec-eslint.md',
        subgroup: 'Tier-Exec',
        description: '機械配置任務的典型路由' },
      { order: 502, slug: 'ex-tier-exec-rename',
        title: 'Tier-Exec：跨檔案重命名', titleEn: 'Tier-Exec: Cross-file Rename',
        source: 'examples/02-tier-exec-rename.md',
        subgroup: 'Tier-Exec',
        description: '上下文寬但判斷低 → 仍可派 Exec' },
      { order: 503, slug: 'ex-tier-mid-refactor',
        title: 'Tier-Mid：CQRS 重構', titleEn: 'Tier-Mid: CQRS Refactor',
        source: 'examples/03-tier-mid-refactor.md',
        subgroup: 'Tier-Mid',
        description: '中等判斷 + 中等風險的典型' },
      { order: 504, slug: 'ex-tier-a-auth',
        title: 'Tier-A：設計 SSO + MFA', titleEn: 'Tier-A: SSO + MFA Design',
        source: 'examples/04-tier-a-auth-design.md',
        subgroup: 'Tier-A',
        description: '三個條件同時觸發 Tier-A' },
      { order: 505, slug: 'ex-borderline',
        title: '邊界案例：cursor pagination', titleEn: 'Borderline: Cursor Pagination',
        source: 'examples/05-borderline-case.md',
        subgroup: 'Borderline',
        description: '保守路遊原則的應用時機' },
    ],
  },
];
