import { useState, useMemo, useEffect } from 'react';
import { Link } from 'react-router-dom';
import Nav from '@/components/Nav';
import { useLang } from '@/i18n/useLang';
import { route, DIMENSIONS, PRESETS, getThresholdHints, type Scoring, type Score } from '@/lib/route';
import PentagonChart from '@/components/PentagonChart';
import { ROLES, FLOWS, buildPrompt, type RoleId, type FlowId } from '@/lib/promptBuilder';

const TIER_COLOR: Record<string, string> = {
  'Tier-A':    'bg-fuchsia-50 dark:bg-fuchsia-950/40 text-fuchsia-900 dark:text-fuchsia-200 border-fuchsia-300 dark:border-fuchsia-800',
  'Tier-Mid':  'bg-cyan-50 dark:bg-cyan-950/40 text-cyan-900 dark:text-cyan-200 border-cyan-300 dark:border-cyan-800',
  'Tier-Exec': 'bg-emerald-50 dark:bg-emerald-950/40 text-emerald-900 dark:text-emerald-200 border-emerald-300 dark:border-emerald-800',
};

const TIER_LABELS: Record<string, { zh: string; en: string }> = {
  'Tier-A':    { zh: 'Tier-A · 判斷層', en: 'Tier-A · Judgment' },
  'Tier-Mid':  { zh: 'Tier-Mid · 審查層', en: 'Tier-Mid · Review' },
  'Tier-Exec': { zh: 'Tier-Exec · 執行層', en: 'Tier-Exec · Execute' },
};

function tierLabel(tier: string, lang: 'zh' | 'en'): string {
  return TIER_LABELS[tier]?.[lang] ?? tier;
}

const DEFAULT_SCORING: Scoring = { judgment: 3, context: 3, risk: 3, verifiability: 3, creativity: 3 };

function generateHandoff(task: string, scoring: Scoring, tier: string, reason: string, lang: 'zh' | 'en'): string {
  const ts = new Date().toISOString();
  if (lang === 'en') {
    return `# Handoff: ${task.slice(0, 60)}${task.length > 60 ? '…' : ''}

> Generated by gstack-plus playground on ${ts}
> Routed to: **${tier}**

## Task Description

${task}

## 5-Dimension Scoring

| Dimension | Score |
|-----------|-------|
| Judgment | ${scoring.judgment} |
| Context Width | ${scoring.context} |
| Risk | ${scoring.risk} |
| Verifiability | ${scoring.verifiability} |
| Creativity | ${scoring.creativity} |

## Routing Decision

- **Tier**: ${tier}
- **Reason**: ${reason}

## Instructions for ${tier} (fill in before dispatching)

### Scope Lock
- [ ] (List file paths this task is allowed to modify)

### Acceptance Criteria
- [ ] (List verifiable success conditions)

### Forbidden Actions
- [ ] (Modify files outside the scope lock)
- [ ] (Claim completion without evidence)
`;
  }

  return `# Handoff: ${task.slice(0, 60)}${task.length > 60 ? '…' : ''}

> Generated by gstack-plus playground on ${ts}
> Routed to: **${tier}**

## 任務描述

${task}

## 5 維評分

| 維度 | 分數 |
|------|------|
| 判斷強度 | ${scoring.judgment} |
| 上下文寬度 | ${scoring.context} |
| 風險權重 | ${scoring.risk} |
| 可驗證性 | ${scoring.verifiability} |
| 創意密度 | ${scoring.creativity} |

## 路由決策

- **Tier**: ${tier}
- **原因**: ${reason}

## 給 ${tier} 的指令（待你填寫）

### Scope Lock
- [ ] (列出本任務允許修改的檔案路徑)

### 完成標準
- [ ] (列出可驗證的成功條件)

### 禁止事項
- [ ] (跨此 Scope Lock 修改其他檔案)
- [ ] (跳過 evidence 直接宣稱完成)
`;
}

export default function Playground() {
  const [lang] = useLang();
  const [task, setTask] = useState('');
  const [scoring, setScoring] = useState<Scoring>(DEFAULT_SCORING);
  const [selectedRole, setSelectedRole] = useState<RoleId>('developer');
  const [selectedFlow, setSelectedFlow] = useState<FlowId>('execute');
  const [promptCopied, setPromptCopied] = useState(false);
  const [enhanced, setEnhanced] = useState(false);
  const [openHint, setOpenHint] = useState<string | null>(null);
  const [conservativeWarningDismissed, setConservativeWarningDismissed] = useState(false);

  // ─── Cost Calculator state ───
  const [costTaskCount, setCostTaskCount] = useState(100);
  const [costExecPct, setCostExecPct] = useState(45);
  const [costMidPct, setCostMidPct] = useState(35);
  const [costAPct, setCostAPct] = useState(20);

  // ─── URL state sync (HashRouter-safe) ───
  // HashRouter URL: https://.../#/playground?t=...&s=...
  useEffect(() => {
    const hash = window.location.hash;
    const qIdx = hash.indexOf('?');
    if (qIdx < 0) return;
    const params = new URLSearchParams(hash.slice(qIdx + 1));
    const t = params.get('t');
    const s = params.get('s');
    if (t) setTask(decodeURIComponent(t));
    if (s) {
      const parts = s.split(',').map(n => parseInt(n, 10));
      if (parts.length === 5 && parts.every(n => n >= 1 && n <= 5)) {
        setScoring({
          judgment: parts[0] as Score,
          context: parts[1] as Score,
          risk: parts[2] as Score,
          verifiability: parts[3] as Score,
          creativity: parts[4] as Score,
        });
      }
    }
  }, []);

  useEffect(() => {
    const hash = window.location.hash;
    const qIdx = hash.indexOf('?');
    const route = qIdx >= 0 ? hash.slice(0, qIdx) : hash;
    const params = new URLSearchParams();
    if (task) params.set('t', task);
    params.set('s', `${scoring.judgment},${scoring.context},${scoring.risk},${scoring.verifiability},${scoring.creativity}`);
    const newHash = `${route}?${params.toString()}`;
    if (window.location.hash !== newHash) {
      window.history.replaceState(null, '', newHash);
    }
  }, [task, scoring]);

  // ─── Share button ───
  const [shareCopied, setShareCopied] = useState(false);
  const copyShareUrl = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href);
      setShareCopied(true);
      setTimeout(() => setShareCopied(false), 1500);
    } catch { /* clipboard unavailable */ }
  };

  const decision = useMemo(() => route(scoring, lang), [scoring, lang]);
  const updateScore = (key: keyof Scoring, value: number) =>
    setScoring(prev => ({ ...prev, [key]: value as Score }));

  const downloadHandoff = () => {
    const md = generateHandoff(task || '(no task description provided)', scoring, decision.tier, decision.reason, lang);
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `handoff-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-background">
      <Nav />
      <div className="max-w-6xl mx-auto px-5 sm:px-8 py-10 sm:py-16">
        <div className="mb-10">
          <div className="text-xs uppercase tracking-widest text-muted mb-2">Playground</div>
          <h1 className="font-display text-3xl sm:text-5xl text-ink leading-tight mb-3">
            {lang === 'zh' ? '在瀏覽器裡試一試分類器。' : 'Try the classifier in your browser.'}
          </h1>
          <p className="text-base text-muted leading-relaxed max-w-2xl">
            {lang === 'zh'
              ? '無需安裝，無需 API key。移動滑桿，實時看到路由變化。準備好後下載 handoff 文件，直接發給模型。'
              : 'No install. No API key. Move the sliders, watch the routing change in real time. Download the handoff doc when you\'re ready to ship the task to a model.'}
          </p>
        </div>

        {/* Presets */}
        <div className="mb-8">
          <div className="text-xs uppercase tracking-widest text-muted mb-3">
            {lang === 'zh' ? '快速載入示例' : 'Quick load examples'}
          </div>
          <div className="flex flex-wrap gap-2">
            {PRESETS.map(p => {
              const tierColor =
                p.label.startsWith('Exec') ? 'border-emerald-200 dark:border-emerald-800 hover:border-emerald-400 dark:hover:border-emerald-600 text-emerald-800 dark:text-emerald-300' :
                p.label.startsWith('A ·') || p.label.startsWith('A·') ? 'border-fuchsia-200 dark:border-fuchsia-800 hover:border-fuchsia-400 dark:hover:border-fuchsia-600 text-fuchsia-800 dark:text-fuchsia-300' :
                p.label.startsWith('Border') ? 'border-amber-200 dark:border-amber-800 hover:border-amber-400 dark:hover:border-amber-600 text-amber-800 dark:text-amber-300' :
                'border-cyan-200 dark:border-cyan-800 hover:border-cyan-400 dark:hover:border-cyan-600 text-cyan-800 dark:text-cyan-300';
              return (
                <button
                  key={p.label}
                  onClick={() => { setTask(p.task); setScoring(p.scoring); }}
                  className={`px-3 py-1.5 text-xs rounded-full border bg-background hover:bg-surface transition-colors ${tierColor}`}
                >
                  {p.label}
                </button>
              );
            })}
          </div>
        </div>

        <div className="grid lg:grid-cols-[1fr_1fr] gap-10">
          {/* Inputs */}
          <div>
            <label className="block mb-6">
              <div className="text-xs uppercase tracking-widest text-muted mb-2">
                {lang === 'zh' ? '任務描述' : 'Task Description'}
              </div>
              <textarea
                value={task}
                onChange={e => setTask(e.target.value)}
                rows={4}
                placeholder="例：Refactor the auth middleware to support OAuth..."
                className="w-full p-3 border border-neutral-300 dark:border-[#383838] rounded-lg font-body text-sm resize-none focus:outline-none focus:border-ink bg-background text-ink placeholder:text-muted"
              />
            </label>

            <div className="space-y-5">
              {DIMENSIONS.map(d => (
                <div key={d.key}>
                  <div className="flex justify-between items-baseline mb-1.5">
                    <div className="flex items-center gap-1.5">
                      <label className="text-sm font-medium text-ink">
                        {lang === 'en' ? d.labelEn : d.label}
                      </label>
                      <button
                        onClick={() => setOpenHint(openHint === d.key ? null : d.key)}
                        className="text-[10px] text-muted hover:text-ink border border-neutral-200 dark:border-[#2A2A2A] hover:border-neutral-400 dark:hover:border-[#444444] rounded px-1 py-0 leading-4 transition-colors"
                        title={lang === 'en' ? 'See examples' : '看示例'}
                      >
                        {openHint === d.key ? '▲' : '?'}
                      </button>
                    </div>
                    <span className="font-display text-xl text-ink tabular-nums">{scoring[d.key]}</span>
                  </div>
                  <input
                    type="range"
                    min={1} max={5} step={1}
                    value={scoring[d.key]}
                    onChange={e => updateScore(d.key, parseInt(e.target.value))}
                    className="w-full accent-black"
                  />
                  <div className="text-[11px] text-muted mt-1">
                    {lang === 'en' ? d.hintEn : d.hint}
                  </div>
                  {openHint === d.key && (
                    <div className="mt-2 rounded-lg bg-surface border border-neutral-200 dark:border-[#2A2A2A] p-3 space-y-2">
                      {d.examples.map(ex => (
                        <div key={ex.score} className="flex gap-2 text-[11px]">
                          <span className="font-display font-bold text-ink w-4 shrink-0">{ex.score}</span>
                          <span className="text-muted leading-snug">
                            {lang === 'en' ? ex.en : ex.zh}
                          </span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Result */}
          <div className="lg:sticky lg:top-8 self-start">
            <div className="text-xs uppercase tracking-widest text-muted mb-3">
              {lang === 'zh' ? '路由決策' : 'Routing decision'}
            </div>
            <div className={`rounded-2xl border-2 p-6 ${TIER_COLOR[decision.tier]}`}>
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1 min-w-0">
                  <div className="font-display text-4xl mb-2">{tierLabel(decision.tier, lang)}</div>
                  <div className="text-sm leading-relaxed mb-4">{decision.reason}</div>
                  {decision.triggeredRules.length > 0 && (
                    <ul className="text-xs space-y-0.5">
                      {decision.triggeredRules.map(r => <li key={r}>• {r}</li>)}
                    </ul>
                  )}
                </div>
                <PentagonChart scoring={scoring} tier={decision.tier} lang={lang} />
              </div>
            </div>

            {/* Threshold hints */}
            {(() => {
              const hints = getThresholdHints(scoring, decision.tier, lang);
              const isBoundary = decision.tier === 'Tier-Exec' && (scoring.judgment === 2 || scoring.context === 2 || scoring.verifiability === 4)
                || decision.tier === 'Tier-Mid' && (scoring.judgment === 3 || scoring.risk === 3 || scoring.creativity === 3)
                || decision.tier === 'Tier-A' && (scoring.judgment === 4 || scoring.risk === 4 || scoring.creativity === 4);
              if (hints.length === 0 && !isBoundary) return null;
              return (
                <div className="mt-3 space-y-1.5">
                  {hints.map((h, i) => {
                    const tierColors: Record<string, string> = {
                      'Tier-A': 'text-fuchsia-700 dark:text-fuchsia-300 bg-fuchsia-50 dark:bg-fuchsia-950/30 border-fuchsia-200 dark:border-fuchsia-800',
                      'Tier-Exec': 'text-emerald-700 dark:text-emerald-300 bg-emerald-50 dark:bg-emerald-950/30 border-emerald-200 dark:border-emerald-800',
                    };
                    const cls = tierColors[h.targetTier] ?? 'text-cyan-700 dark:text-cyan-300 bg-cyan-50 dark:bg-cyan-950/30 border-cyan-200 dark:border-cyan-800';
                    return (
                      <div key={i} className={`text-xs rounded-lg border px-3 py-2 ${cls}`}>
                        <span className="opacity-70">
                          {lang === 'en' ? `${h.targetTier} is 1 step away:` : `距 ${h.targetTier} 僅差：`}
                        </span>
                        {' '}
                        <span className="font-medium">
                          {h.changes.map((c, ci) => {
                            const m = c.match(/(\d+)→(\d+)/);
                            const dir = m && parseInt(m[2]) > parseInt(m[1]) ? '↑' : '↓';
                            return (ci > 0 ? ' · ' : '') + dir + ' ' + c;
                          }).join('')}
                        </span>
                      </div>
                    );
                  })}
                  {isBoundary && hints.length === 0 && (
                    <div className="text-xs rounded-lg border border-amber-200 dark:border-amber-800 bg-amber-50 dark:bg-amber-950/30 px-3 py-2 text-amber-800 dark:text-amber-300">
                      <span className="opacity-70">
                        {lang === 'en' ? '⚠ Boundary case — consider routing up.' : '⚠ 邊界案例 — 考慮向上路由。'}
                      </span>
                    </div>
                  )}
                </div>
              );
            })()}

            {/* Conservative Routing Warning */}
            {(() => {
              const j = scoring.judgment;
              const r = scoring.risk;
              const showWarning = (j === 3 || r === 3) && decision.tier !== 'Tier-A';
              
              if (!showWarning) return null;
              
              const higherTier = decision.tier === 'Tier-Exec' ? 'Tier-Mid' : 'Tier-A';
              const higherTierLabel = tierLabel(higherTier, lang);
              
              const hash = `${j},${r},${scoring.context},${scoring.verifiability},${scoring.creativity}`;
              
              if (conservativeWarningDismissed) return null;
              
              const handleDismiss = () => {
                try {
                  localStorage.setItem('dismissedConservativeWarning', hash);
                } catch {}
                setConservativeWarningDismissed(true);
              };
              
              const handleUpgrade = () => {
                if (j === 3) updateScore('judgment', 4);
                else if (r === 3) updateScore('risk', 4);
              };
              
              return (
                <div className="mt-4 rounded-lg border-2 border-amber-300 dark:border-amber-700 bg-amber-50 dark:bg-amber-950/30 p-4 space-y-3">
                  <div className="text-sm font-medium text-amber-700 dark:text-amber-400">
                    {lang === 'zh' ? '⚠️ 保守路由建議' : '⚠️ Conservative Routing Suggested'}
                  </div>
                  <div className="text-xs text-amber-900 dark:text-amber-200 leading-relaxed">
                    {lang === 'zh'
                      ? `J = ${j} 或 R = ${r} 處於邊界值。Series 6 實驗顯示，這兩個維度的 ±1 誤差各有 32–33% 概率引發路由層級錯誤。若任務影響生產環境，建議直接升至 ${higherTierLabel}。`
                      : `J = ${j} or R = ${r} is a boundary value. Series 6 experiments show ±1 scoring errors on these dimensions cause routing mistakes 32–33% of the time. If this task affects production, consider routing up to ${higherTierLabel}.`}
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <button
                      onClick={handleDismiss}
                      className="rounded-full px-3 py-1.5 text-xs border border-amber-300 dark:border-amber-700 text-amber-800 dark:text-amber-200 hover:bg-amber-100 dark:hover:bg-amber-900/50 transition-colors"
                    >
                      {lang === 'zh' ? '忽略，保持當前路由' : 'Dismiss, keep current routing'}
                    </button>
                    <button
                      onClick={handleUpgrade}
                      className="rounded-full px-3 py-1.5 text-xs bg-amber-600 hover:bg-amber-700 text-white transition-colors"
                    >
                      {lang === 'zh' ? `升至 ${higherTierLabel}` : `Route to ${higherTierLabel}`}
                    </button>
                  </div>
                  <div className="pt-1">
                    <a
                      href="#/doc/routing-confidence-guide"
                      className="text-[11px] text-amber-700 dark:text-amber-400 hover:underline"
                    >
                      {lang === 'zh' ? '了解更多 → 路由信心指南' : 'Learn more → Routing Confidence Guide'}
                    </a>
                  </div>
                </div>
              );
            })()}

            <div className="mt-6 flex flex-wrap gap-3">
              <button
                onClick={copyShareUrl}
                className="rounded-full px-6 py-3 text-sm border border-neutral-300 dark:border-[#383838] text-ink hover:bg-neutral-50 dark:hover:bg-[#1a1a1a] transition-colors"
              >
                {shareCopied
                  ? (lang === 'zh' ? '✓ 已複製' : '✓ Link copied')
                  : (lang === 'zh' ? '分享此評分' : 'Share this scoring')}
              </button>
              <button
                onClick={downloadHandoff}
                className="rounded-full px-6 py-3 text-sm border border-neutral-300 dark:border-[#383838] text-ink hover:bg-neutral-50 dark:hover:bg-[#1a1a1a] transition-colors bg-ink text-white dark:text-black hover:scale-[1.03]"
              >
                {lang === 'zh' ? '下載 Handoff 文件' : 'Download handoff doc'}
              </button>
              <Link
                to="/doc/cli"
                className="rounded-full px-6 py-3 text-sm border border-neutral-300 dark:border-[#383838] text-ink hover:bg-neutral-50 dark:hover:bg-[#1a1a1a] transition-colors"
              >
                {lang === 'zh' ? '改用 CLI →' : 'Use the CLI instead →'}
              </Link>
            </div>

            <div className="mt-8 text-xs text-muted leading-relaxed">
              <div className="font-medium text-ink mb-1">
                {lang === 'zh' ? '路由規則' : 'Routing rules'}
              </div>
              <code className="block bg-neutral-100 dark:bg-[#1e1e1e] p-2 rounded text-[11px] font-mono whitespace-pre">
{`judgment≥4 OR risk≥4 OR creativity≥4 → Tier-A
judgment≤2 AND context≤2 AND verif≥4  → Tier-Exec
else                                  → Tier-Mid`}
              </code>
            </div>
          </div>
        </div>
      </div>

      {/* ── Prompt Builder ───────────────────────────────────────── */}
      <div className="max-w-6xl mx-auto px-5 sm:px-8 pb-16 pt-4">
        <div className="border-t border-neutral-200 dark:border-[#2A2A2A] pt-12">
          <div className="text-xs uppercase tracking-widest text-muted mb-2">Prompt Builder</div>
          <h2 className="font-display text-2xl sm:text-3xl text-ink mb-2">
            {lang === 'zh' ? '生成可直接使用的 Prompt' : 'Generate a ready-to-use prompt'}
          </h2>
          <p className="text-sm text-muted mb-8 max-w-2xl">
            {lang === 'zh'
              ? '選擇角色和工作模式，系統自動把任務描述 + 路由結果組合成一份結構化 prompt，可以直接貼進任何 AI 助手。'
              : 'Choose a role and flow. The system assembles your task + routing result into a structured prompt you can paste directly into any AI assistant.'}
          </p>

          {/* Step 1: Role */}
          <div className="mb-8">
            <div className="text-xs uppercase tracking-widest text-muted mb-3">
              {lang === 'zh' ? '步驟 1 — 選角色' : 'Step 1 — Choose a role'}
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2">
              {ROLES.map(r => (
                <button
                  key={r.id}
                  onClick={() => setSelectedRole(r.id)}
                  className={`rounded-xl border p-3 text-left transition-colors ${
                    selectedRole === r.id
                      ? 'border-ink bg-surface'
                      : 'border-neutral-200 dark:border-[#2A2A2A] hover:border-neutral-400'
                  }`}
                >
                  <div className="text-xs font-medium text-ink mb-1">
                    {lang === 'zh' ? r.label : r.labelEn}
                  </div>
                  <div className="text-[10px] text-muted leading-snug">
                    {lang === 'zh' ? r.description : r.descriptionEn}
                  </div>
                  <div className="mt-2">
                    <span className={`text-[10px] px-1.5 py-0.5 rounded-full ${
                      r.tier === 'Tier-A' || r.tier === 'Tier-A/Mid' ? 'bg-fuchsia-100 text-fuchsia-700' :
                      r.tier === 'Tier-Exec' ? 'bg-emerald-100 text-emerald-700' :
                      'bg-cyan-100 text-cyan-700'
                    }`}>
                      {r.tier}
                    </span>
                  </div>
                </button>
              ))}
            </div>
          </div>

          {/* Step 2: Flow */}
          <div className="mb-8">
            <div className="text-xs uppercase tracking-widest text-muted mb-3">
              {lang === 'zh' ? '步驟 2 — 選工作模式' : 'Step 2 — Choose a flow'}
            </div>
            <div className="flex flex-wrap gap-2">
              {FLOWS.map(f => (
                <button
                  key={f.id}
                  onClick={() => setSelectedFlow(f.id)}
                  className={`rounded-full px-4 py-2 text-sm border transition-colors ${
                    selectedFlow === f.id
                      ? 'border-ink bg-ink text-white dark:text-black'
                      : 'border-neutral-300 dark:border-[#383838] hover:border-ink text-ink'
                  }`}
                >
                  {lang === 'zh' ? f.label : f.labelEn}
                  <span className="ml-2 text-[11px] opacity-60">
                    {lang === 'zh' ? f.description : f.descriptionEn}
                  </span>
                </button>
              ))}
            </div>
          </div>

          {/* Step 2.5: Enhanced Mode Toggle */}
          <div className="mb-8">
            <div className="flex items-center gap-3">
              <button
                onClick={() => setEnhanced(e => !e)}
                className={`relative inline-flex h-5 w-9 shrink-0 cursor-pointer rounded-full border-2 transition-colors ${
                  enhanced ? 'border-amber-500 bg-amber-500' : 'border-neutral-300 dark:border-[#444444] bg-neutral-200 dark:bg-[#2a2a2a]'
                }`}
                role="switch"
                aria-checked={enhanced}
              >
                <span className={`pointer-events-none inline-block h-3.5 w-3.5 translate-y-[-1px] rounded-full bg-white shadow transition-transform ${enhanced ? 'translate-x-4' : 'translate-x-0'}`} />
              </button>
              <div>
                <span className="text-xs font-medium text-ink">
                  {lang === 'zh' ? 'S1 增強模式' : 'S1 Enhanced'}
                </span>
                {enhanced && (
                  <span className="ml-2 text-[10px] px-1.5 py-0.5 rounded-full bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-400">
                    {lang === 'zh' ? 'Sonnet 15.0/15 > Opus 12.7/15' : 'Sonnet 15.0/15 > Opus 12.7/15'}
                  </span>
                )}
              </div>
            </div>
            <p className="mt-1.5 text-[11px] text-muted max-w-xl">
              {lang === 'zh'
                ? '在角色說明前加入「資深工程師身份 + 主動揭示風險」的系統提示。Series 3 實驗顯示這讓 Sonnet 超過 Opus（15.0 vs 12.7/15），節省 86% 費用。適用 Tier-Mid 任務。'
                : 'Prepends a staff-engineer identity + proactive risk surfacing primer before the role instructions. Series 3 shows this lets Sonnet beat Opus (15.0 vs 12.7/15) at 14% of the cost. Best for Tier-Mid tasks.'}
            </p>
            {!enhanced && decision.tier === 'Tier-Mid' && (
              <p className="mt-1.5 text-[11px] text-amber-600">
                {lang === 'zh' ? '💡 偵測到 Tier-Mid — 建議開啟 S1 增強模式' : '💡 Tier-Mid detected — S1 Enhanced recommended'}
              </p>
            )}
          </div>

          {/* Step 3: Generated Prompt */}
          <div>
            <div className="flex items-center justify-between mb-3">
              <div className="text-xs uppercase tracking-widest text-muted">
                {lang === 'zh' ? '步驟 3 — 你的 Prompt（複製後直接用）' : 'Step 3 — Your prompt (ready to paste)'}
              </div>
              <button
                onClick={async () => {
                  const prompt = buildPrompt(task, scoring, decision.tier, selectedRole, selectedFlow, lang, enhanced);
                  try {
                    await navigator.clipboard.writeText(prompt);
                    setPromptCopied(true);
                    setTimeout(() => setPromptCopied(false), 1500);
                  } catch { /* clipboard unavailable */ }
                }}
                className="rounded-full px-4 py-1.5 text-xs border border-neutral-300 dark:border-[#383838] hover:border-ink transition-colors"
              >
                {promptCopied
                  ? (lang === 'zh' ? '✓ 已複製' : '✓ Copied')
                  : (lang === 'zh' ? '複製 Prompt' : 'Copy prompt')}
              </button>
            </div>
            <pre className="bg-surface border border-neutral-200 dark:border-[#2A2A2A] rounded-xl p-5 text-xs font-mono leading-relaxed overflow-auto max-h-96 whitespace-pre-wrap">
              {buildPrompt(task, scoring, decision.tier, selectedRole, selectedFlow, lang, enhanced)}
            </pre>
            <p className="mt-3 text-xs text-muted">
              {lang === 'zh'
                ? '💡 這是 System Prompt。配合「Download handoff doc」使用效果最好：handoff doc 作為 User 消息，這個作為 System 消息。'
                : '💡 This is your System Prompt. Pair it with the handoff doc for best results: handoff doc as the User message, this as the System message.'}
            </p>
          </div>
        </div>
      </div>

      {/* ── Cost Savings Estimator ───────────────────────────────── */}
      <div className="max-w-6xl mx-auto px-5 sm:px-8 pb-16 pt-4">
        <div className="border-t border-neutral-200 dark:border-[#2A2A2A] pt-12">
          <div className="text-xs uppercase tracking-widest text-muted mb-2">
            {lang === 'zh' ? '成本節省估算' : 'Cost Savings Estimator'}
          </div>
          <h2 className="font-display text-2xl sm:text-3xl text-ink mb-8">
            {lang === 'zh' ? '💰 成本節省估算' : '💰 Cost Savings Estimator'}
          </h2>

          <div className="bg-neutral-50 dark:bg-neutral-900/50 rounded-xl p-6 space-y-6">
            {/* Input Row */}
            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
              {/* Task Count */}
              <div>
                <label className="block text-xs text-muted mb-2">
                  {lang === 'zh' ? '每月 AI 任務總數' : 'Monthly AI Tasks'}
                </label>
                <input
                  type="number"
                  min={1}
                  value={costTaskCount}
                  onChange={e => setCostTaskCount(Math.max(1, parseInt(e.target.value) || 1))}
                  className="w-full p-2 border border-neutral-300 dark:border-[#383838] rounded bg-background text-ink font-display text-lg focus:outline-none focus:border-ink"
                />
              </div>

              {/* Exec % */}
              <div>
                <label className="block text-xs text-muted mb-2">
                  {lang === 'zh' ? 'Exec %' : 'Exec %'}
                </label>
                <input
                  type="number"
                  min={0}
                  max={100}
                  value={costExecPct}
                  onChange={e => setCostExecPct(Math.min(100, Math.max(0, parseInt(e.target.value) || 0)))}
                  className="w-full p-2 border border-neutral-300 dark:border-[#383838] rounded bg-background text-ink font-display text-lg focus:outline-none focus:border-ink"
                />
              </div>

              {/* Mid % */}
              <div>
                <label className="block text-xs text-muted mb-2">
                  {lang === 'zh' ? 'Mid %' : 'Mid %'}
                </label>
                <input
                  type="number"
                  min={0}
                  max={100}
                  value={costMidPct}
                  onChange={e => setCostMidPct(Math.min(100, Math.max(0, parseInt(e.target.value) || 0)))}
                  className="w-full p-2 border border-neutral-300 dark:border-[#383838] rounded bg-background text-ink font-display text-lg focus:outline-none focus:border-ink"
                />
              </div>

              {/* A % */}
              <div>
                <label className="block text-xs text-muted mb-2">
                  {lang === 'zh' ? 'A %' : 'A %'}
                </label>
                <input
                  type="number"
                  min={0}
                  max={100}
                  value={costAPct}
                  onChange={e => setCostAPct(Math.min(100, Math.max(0, parseInt(e.target.value) || 0)))}
                  className="w-full p-2 border border-neutral-300 dark:border-[#383838] rounded bg-background text-ink font-display text-lg focus:outline-none focus:border-ink"
                />
              </div>
            </div>

            {/* Validation / Output */}
            {(() => {
              const totalPct = costExecPct + costMidPct + costAPct;
              if (totalPct !== 100) {
                return (
                  <div className="text-sm text-red-600 dark:text-red-400 border border-red-200 dark:border-red-800 bg-red-50 dark:bg-red-950/30 rounded-lg p-3">
                    {lang === 'zh'
                      ? `❌ 三個 Tier 的比例之和必須為 100%（當前：${totalPct}%）`
                      : `❌ Three tier percentages must sum to 100% (current: ${totalPct}%)`}
                  </div>
                );
              }

              const COST = { 'Tier-A': 0.060, 'Tier-Mid': 0.010, 'Tier-Exec': 0.001 };
              const allOpusCost = costTaskCount * COST['Tier-A'];
              const routedCost = costTaskCount * (costExecPct / 100 * COST['Tier-Exec'] + costMidPct / 100 * COST['Tier-Mid'] + costAPct / 100 * COST['Tier-A']);
              const saving = allOpusCost - routedCost;
              const savingPct = Math.round((saving / allOpusCost) * 100);
              const yearlySaving = saving * 12;

              return (
                <div className="space-y-4">
                  {/* Output Numbers */}
                  <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
                    <div className="text-center p-4 bg-white dark:bg-neutral-800 rounded-lg border border-neutral-200 dark:border-[#2A2A2A]">
                      <div className="text-[10px] uppercase tracking-wider text-muted mb-1">
                        {lang === 'zh' ? '當前月均成本' : 'Current Monthly Cost'}
                      </div>
                      <div className="font-display text-3xl text-ink">${allOpusCost.toFixed(2)}</div>
                      <div className="text-[10px] text-muted mt-1">
                        {lang === 'zh' ? '（全部使用 Opus）' : '(All-Opus)'}
                      </div>
                    </div>
                    <div className="text-center p-4 bg-white dark:bg-neutral-800 rounded-lg border border-neutral-200 dark:border-[#2A2A2A]">
                      <div className="text-[10px] uppercase tracking-wider text-muted mb-1">
                        {lang === 'zh' ? '路由後月均成本' : 'Routed Monthly Cost'}
                      </div>
                      <div className="font-display text-3xl text-ink">${routedCost.toFixed(2)}</div>
                    </div>
                    <div className="text-center p-4 bg-white dark:bg-neutral-800 rounded-lg border border-neutral-200 dark:border-[#2A2A2A]">
                      <div className="text-[10px] uppercase tracking-wider text-muted mb-1">
                        {lang === 'zh' ? '月均節省' : 'Monthly Savings'}
                      </div>
                      <div className="font-display text-3xl text-emerald-600 dark:text-emerald-400">${saving.toFixed(2)}</div>
                      <div className="text-[10px] text-muted mt-1">
                        {savingPct}% {lang === 'zh' ? '節省率' : 'savings'}
                      </div>
                    </div>
                    <div className="text-center p-4 bg-white dark:bg-neutral-800 rounded-lg border border-neutral-200 dark:border-[#2A2A2A]">
                      <div className="text-[10px] uppercase tracking-wider text-muted mb-1">
                        {lang === 'zh' ? '年均節省' : 'Yearly Savings'}
                      </div>
                      <div className="font-display text-3xl text-emerald-600 dark:text-emerald-400">${yearlySaving.toFixed(2)}</div>
                    </div>
                  </div>

                  {/* Source Attribution */}
                  <div className="text-[10px] text-muted text-center pt-2">
                    {lang === 'zh'
                      ? '數據來源：Series 1 實驗（3 任務）+ Series 7 成本基準'
                      : 'Based on Series 1 (3-task experiment) + Series 7 cost baseline'}
                  </div>
                </div>
              );
            })()}
          </div>
        </div>
      </div>
    </div>
  );
}
