import { useState, useMemo, useEffect } from 'react';
import { Link } from 'react-router-dom';
import Nav from '@/components/Nav';
import { route, DIMENSIONS, PRESETS, type Scoring, type Score } from '@/lib/route';

const TIER_COLOR: Record<string, string> = {
  'Tier-A':    'bg-fuchsia-50 text-fuchsia-900 border-fuchsia-300',
  'Tier-Mid':  'bg-cyan-50 text-cyan-900 border-cyan-300',
  'Tier-Exec': 'bg-emerald-50 text-emerald-900 border-emerald-300',
};

const DEFAULT_SCORING: Scoring = { judgment: 3, context: 3, risk: 3, verifiability: 3, creativity: 3 };

function generateHandoff(task: string, scoring: Scoring, tier: string, reason: string): string {
  const ts = new Date().toISOString();
  return `# Handoff: ${task.slice(0, 60)}${task.length > 60 ? '…' : ''}

> Generated by gstack-plus playground on ${ts}
> Routed to: **${tier}**

## 任務描述

${task}

## 5 維評分

| 維度 | 分數 |
|------|------|
| 判斷強度 | ${scoring.judgment} |
| 上下文寬度 | ${scoring.context} |
| 風險權重 | ${scoring.risk} |
| 可驗證性 | ${scoring.verifiability} |
| 創意密度 | ${scoring.creativity} |

## 路由決策

- **Tier**: ${tier}
- **原因**: ${reason}

## 給 ${tier} 的指令（待你填寫）

### Scope Lock
- [ ] (列出本任務允許修改的檔案路徑)

### 完成標準
- [ ] (列出可驗證的成功條件)

### 禁止事項
- [ ] (跨此 Scope Lock 修改其他檔案)
- [ ] (跳過 evidence 直接宣稱完成)
`;
}

export default function Playground() {
  const [task, setTask] = useState('');
  const [scoring, setScoring] = useState<Scoring>(DEFAULT_SCORING);

  // ─── URL state sync (HashRouter-safe) ───
  // HashRouter URL: https://.../#/playground?t=...&s=...
  useEffect(() => {
    const hash = window.location.hash;
    const qIdx = hash.indexOf('?');
    if (qIdx < 0) return;
    const params = new URLSearchParams(hash.slice(qIdx + 1));
    const t = params.get('t');
    const s = params.get('s');
    if (t) setTask(decodeURIComponent(t));
    if (s) {
      const parts = s.split(',').map(n => parseInt(n, 10));
      if (parts.length === 5 && parts.every(n => n >= 1 && n <= 5)) {
        setScoring({
          judgment: parts[0] as Score,
          context: parts[1] as Score,
          risk: parts[2] as Score,
          verifiability: parts[3] as Score,
          creativity: parts[4] as Score,
        });
      }
    }
  }, []);

  useEffect(() => {
    const hash = window.location.hash;
    const qIdx = hash.indexOf('?');
    const route = qIdx >= 0 ? hash.slice(0, qIdx) : hash;
    const params = new URLSearchParams();
    if (task) params.set('t', task);
    params.set('s', `${scoring.judgment},${scoring.context},${scoring.risk},${scoring.verifiability},${scoring.creativity}`);
    const newHash = `${route}?${params.toString()}`;
    if (window.location.hash !== newHash) {
      window.history.replaceState(null, '', newHash);
    }
  }, [task, scoring]);

  // ─── Share button ───
  const [shareCopied, setShareCopied] = useState(false);
  const copyShareUrl = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href);
      setShareCopied(true);
      setTimeout(() => setShareCopied(false), 1500);
    } catch { /* clipboard unavailable */ }
  };

  const decision = useMemo(() => route(scoring), [scoring]);
  const updateScore = (key: keyof Scoring, value: number) =>
    setScoring(prev => ({ ...prev, [key]: value as Score }));

  const downloadHandoff = () => {
    const md = generateHandoff(task || '(no task description provided)', scoring, decision.tier, decision.reason);
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `handoff-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-background">
      <Nav />
      <div className="max-w-6xl mx-auto px-5 sm:px-8 py-10 sm:py-16">
        <div className="mb-10">
          <div className="text-xs uppercase tracking-widest text-muted mb-2">Playground</div>
          <h1 className="font-display text-3xl sm:text-5xl text-ink leading-tight mb-3">
            Try the classifier in your browser.
          </h1>
          <p className="text-base text-muted leading-relaxed max-w-2xl">
            No install. No API key. Move the sliders, watch the routing change in real time.
            Download the handoff doc when you're ready to ship the task to a model.
          </p>
        </div>

        {/* Presets */}
        <div className="mb-8">
          <div className="text-xs uppercase tracking-widest text-muted mb-3">Quick load</div>
          <div className="flex flex-wrap gap-2">
            {PRESETS.map(p => (
              <button
                key={p.label}
                onClick={() => { setTask(p.task); setScoring(p.scoring); }}
                className="px-3 py-1.5 text-xs rounded-full border border-neutral-300 hover:border-ink hover:bg-neutral-50 transition-colors"
              >
                {p.label}
              </button>
            ))}
          </div>
        </div>

        <div className="grid lg:grid-cols-[1fr_1fr] gap-10">
          {/* Inputs */}
          <div>
            <label className="block mb-6">
              <div className="text-xs uppercase tracking-widest text-muted mb-2">任務描述</div>
              <textarea
                value={task}
                onChange={e => setTask(e.target.value)}
                rows={4}
                placeholder="例：Refactor the auth middleware to support OAuth..."
                className="w-full p-3 border border-neutral-300 rounded-lg font-body text-sm resize-none focus:outline-none focus:border-ink"
              />
            </label>

            <div className="space-y-5">
              {DIMENSIONS.map(d => (
                <div key={d.key}>
                  <div className="flex justify-between items-baseline mb-1.5">
                    <label className="text-sm font-medium text-ink">{d.label}</label>
                    <span className="font-display text-xl text-ink tabular-nums">{scoring[d.key]}</span>
                  </div>
                  <input
                    type="range"
                    min={1} max={5} step={1}
                    value={scoring[d.key]}
                    onChange={e => updateScore(d.key, parseInt(e.target.value))}
                    className="w-full accent-black"
                  />
                  <div className="text-[11px] text-muted mt-1">{d.hint}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Result */}
          <div className="lg:sticky lg:top-8 self-start">
            <div className="text-xs uppercase tracking-widest text-muted mb-3">Routing decision</div>
            <div className={`rounded-2xl border-2 p-6 ${TIER_COLOR[decision.tier]}`}>
              <div className="font-display text-4xl mb-2">{decision.tier}</div>
              <div className="text-sm leading-relaxed mb-4">{decision.reason}</div>
              {decision.triggeredRules.length > 0 && (
                <ul className="text-xs space-y-0.5 mb-4">
                  {decision.triggeredRules.map(r => <li key={r}>• {r}</li>)}
                </ul>
              )}
            </div>

            <div className="mt-6 flex flex-wrap gap-3">
              <button
                onClick={copyShareUrl}
                className="rounded-full px-6 py-3 text-sm border border-neutral-300 text-ink hover:bg-neutral-50 transition-colors"
              >
                {shareCopied ? '✓ Link copied' : 'Share this scoring'}
              </button>
              <button
                onClick={downloadHandoff}
                className="rounded-full px-6 py-3 text-sm bg-ink text-white hover:scale-[1.03] transition-transform"
              >
                Download handoff doc
              </button>
              <Link
                to="/doc/cli"
                className="rounded-full px-6 py-3 text-sm border border-neutral-300 text-ink hover:bg-neutral-50 transition-colors"
              >
                Use the CLI instead →
              </Link>
            </div>

            <div className="mt-8 text-xs text-muted leading-relaxed">
              <div className="font-medium text-ink mb-1">Routing rules</div>
              <code className="block bg-neutral-100 p-2 rounded text-[11px] font-mono whitespace-pre">
{`judgment≥4 OR risk≥4 OR creativity≥4 → Tier-A
judgment≤2 AND context≤2 AND verif≥4  → Tier-Exec
else                                  → Tier-Mid`}
              </code>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
