import { useState, useMemo, useEffect } from 'react';
import { Link } from 'react-router-dom';
import Nav from '@/components/Nav';
import { useLang } from '@/i18n/useLang';
import { route, DIMENSIONS, PRESETS, getThresholdHints, type Scoring, type Score } from '@/lib/route';
import PentagonChart from '@/components/PentagonChart';
import { ROLES, FLOWS, buildPrompt, type RoleId, type FlowId } from '@/lib/promptBuilder';

const TIER_COLOR: Record<string, string> = {
  'Tier-A':    'bg-fuchsia-50 text-fuchsia-900 border-fuchsia-300',
  'Tier-Mid':  'bg-cyan-50 text-cyan-900 border-cyan-300',
  'Tier-Exec': 'bg-emerald-50 text-emerald-900 border-emerald-300',
};

const TIER_LABELS: Record<string, { zh: string; en: string }> = {
  'Tier-A':    { zh: 'Tier-A · 判斷層', en: 'Tier-A · Judgment' },
  'Tier-Mid':  { zh: 'Tier-Mid · 審查層', en: 'Tier-Mid · Review' },
  'Tier-Exec': { zh: 'Tier-Exec · 執行層', en: 'Tier-Exec · Execute' },
};

function tierLabel(tier: string, lang: 'zh' | 'en'): string {
  return TIER_LABELS[tier]?.[lang] ?? tier;
}

const DEFAULT_SCORING: Scoring = { judgment: 3, context: 3, risk: 3, verifiability: 3, creativity: 3 };

function generateHandoff(task: string, scoring: Scoring, tier: string, reason: string, lang: 'zh' | 'en'): string {
  const ts = new Date().toISOString();
  if (lang === 'en') {
    return `# Handoff: ${task.slice(0, 60)}${task.length > 60 ? '…' : ''}

> Generated by gstack-plus playground on ${ts}
> Routed to: **${tier}**

## Task Description

${task}

## 5-Dimension Scoring

| Dimension | Score |
|-----------|-------|
| Judgment | ${scoring.judgment} |
| Context Width | ${scoring.context} |
| Risk | ${scoring.risk} |
| Verifiability | ${scoring.verifiability} |
| Creativity | ${scoring.creativity} |

## Routing Decision

- **Tier**: ${tier}
- **Reason**: ${reason}

## Instructions for ${tier} (fill in before dispatching)

### Scope Lock
- [ ] (List file paths this task is allowed to modify)

### Acceptance Criteria
- [ ] (List verifiable success conditions)

### Forbidden Actions
- [ ] (Modify files outside the scope lock)
- [ ] (Claim completion without evidence)
`;
  }

  return `# Handoff: ${task.slice(0, 60)}${task.length > 60 ? '…' : ''}

> Generated by gstack-plus playground on ${ts}
> Routed to: **${tier}**

## 任務描述

${task}

## 5 維評分

| 維度 | 分數 |
|------|------|
| 判斷強度 | ${scoring.judgment} |
| 上下文寬度 | ${scoring.context} |
| 風險權重 | ${scoring.risk} |
| 可驗證性 | ${scoring.verifiability} |
| 創意密度 | ${scoring.creativity} |

## 路由決策

- **Tier**: ${tier}
- **原因**: ${reason}

## 給 ${tier} 的指令（待你填寫）

### Scope Lock
- [ ] (列出本任務允許修改的檔案路徑)

### 完成標準
- [ ] (列出可驗證的成功條件)

### 禁止事項
- [ ] (跨此 Scope Lock 修改其他檔案)
- [ ] (跳過 evidence 直接宣稱完成)
`;
}

export default function Playground() {
  const [lang] = useLang();
  const [task, setTask] = useState('');
  const [scoring, setScoring] = useState<Scoring>(DEFAULT_SCORING);
  const [selectedRole, setSelectedRole] = useState<RoleId>('developer');
  const [selectedFlow, setSelectedFlow] = useState<FlowId>('execute');
  const [promptCopied, setPromptCopied] = useState(false);
  const [openHint, setOpenHint] = useState<string | null>(null);

  // ─── URL state sync (HashRouter-safe) ───
  // HashRouter URL: https://.../#/playground?t=...&s=...
  useEffect(() => {
    const hash = window.location.hash;
    const qIdx = hash.indexOf('?');
    if (qIdx < 0) return;
    const params = new URLSearchParams(hash.slice(qIdx + 1));
    const t = params.get('t');
    const s = params.get('s');
    if (t) setTask(decodeURIComponent(t));
    if (s) {
      const parts = s.split(',').map(n => parseInt(n, 10));
      if (parts.length === 5 && parts.every(n => n >= 1 && n <= 5)) {
        setScoring({
          judgment: parts[0] as Score,
          context: parts[1] as Score,
          risk: parts[2] as Score,
          verifiability: parts[3] as Score,
          creativity: parts[4] as Score,
        });
      }
    }
  }, []);

  useEffect(() => {
    const hash = window.location.hash;
    const qIdx = hash.indexOf('?');
    const route = qIdx >= 0 ? hash.slice(0, qIdx) : hash;
    const params = new URLSearchParams();
    if (task) params.set('t', task);
    params.set('s', `${scoring.judgment},${scoring.context},${scoring.risk},${scoring.verifiability},${scoring.creativity}`);
    const newHash = `${route}?${params.toString()}`;
    if (window.location.hash !== newHash) {
      window.history.replaceState(null, '', newHash);
    }
  }, [task, scoring]);

  // ─── Share button ───
  const [shareCopied, setShareCopied] = useState(false);
  const copyShareUrl = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href);
      setShareCopied(true);
      setTimeout(() => setShareCopied(false), 1500);
    } catch { /* clipboard unavailable */ }
  };

  const decision = useMemo(() => route(scoring, lang), [scoring, lang]);
  const updateScore = (key: keyof Scoring, value: number) =>
    setScoring(prev => ({ ...prev, [key]: value as Score }));

  const downloadHandoff = () => {
    const md = generateHandoff(task || '(no task description provided)', scoring, decision.tier, decision.reason, lang);
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `handoff-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-background">
      <Nav />
      <div className="max-w-6xl mx-auto px-5 sm:px-8 py-10 sm:py-16">
        <div className="mb-10">
          <div className="text-xs uppercase tracking-widest text-muted mb-2">Playground</div>
          <h1 className="font-display text-3xl sm:text-5xl text-ink leading-tight mb-3">
            Try the classifier in your browser.
          </h1>
          <p className="text-base text-muted leading-relaxed max-w-2xl">
            No install. No API key. Move the sliders, watch the routing change in real time.
            Download the handoff doc when you're ready to ship the task to a model.
          </p>
        </div>

        {/* Presets */}
        <div className="mb-8">
          <div className="text-xs uppercase tracking-widest text-muted mb-3">
            {lang === 'zh' ? '快速載入示例' : 'Quick load examples'}
          </div>
          <div className="flex flex-wrap gap-2">
            {PRESETS.map(p => {
              const tierColor =
                p.label.startsWith('Exec') ? 'border-emerald-200 hover:border-emerald-400 text-emerald-800' :
                p.label.startsWith('A ·') || p.label.startsWith('A·') ? 'border-fuchsia-200 hover:border-fuchsia-400 text-fuchsia-800' :
                p.label.startsWith('Border') ? 'border-amber-200 hover:border-amber-400 text-amber-800' :
                'border-cyan-200 hover:border-cyan-400 text-cyan-800';
              return (
                <button
                  key={p.label}
                  onClick={() => { setTask(p.task); setScoring(p.scoring); }}
                  className={`px-3 py-1.5 text-xs rounded-full border bg-white hover:bg-neutral-50 transition-colors ${tierColor}`}
                >
                  {p.label}
                </button>
              );
            })}
          </div>
        </div>

        <div className="grid lg:grid-cols-[1fr_1fr] gap-10">
          {/* Inputs */}
          <div>
            <label className="block mb-6">
              <div className="text-xs uppercase tracking-widest text-muted mb-2">
                {lang === 'zh' ? '任務描述' : 'Task Description'}
              </div>
              <textarea
                value={task}
                onChange={e => setTask(e.target.value)}
                rows={4}
                placeholder="例：Refactor the auth middleware to support OAuth..."
                className="w-full p-3 border border-neutral-300 rounded-lg font-body text-sm resize-none focus:outline-none focus:border-ink"
              />
            </label>

            <div className="space-y-5">
              {DIMENSIONS.map(d => (
                <div key={d.key}>
                  <div className="flex justify-between items-baseline mb-1.5">
                    <div className="flex items-center gap-1.5">
                      <label className="text-sm font-medium text-ink">
                        {lang === 'en' ? d.labelEn : d.label}
                      </label>
                      <button
                        onClick={() => setOpenHint(openHint === d.key ? null : d.key)}
                        className="text-[10px] text-muted hover:text-ink border border-neutral-200 hover:border-neutral-400 rounded px-1 py-0 leading-4 transition-colors"
                        title={lang === 'en' ? 'See examples' : '看示例'}
                      >
                        {openHint === d.key ? '▲' : '?'}
                      </button>
                    </div>
                    <span className="font-display text-xl text-ink tabular-nums">{scoring[d.key]}</span>
                  </div>
                  <input
                    type="range"
                    min={1} max={5} step={1}
                    value={scoring[d.key]}
                    onChange={e => updateScore(d.key, parseInt(e.target.value))}
                    className="w-full accent-black"
                  />
                  <div className="text-[11px] text-muted mt-1">
                    {lang === 'en' ? d.hintEn : d.hint}
                  </div>
                  {openHint === d.key && (
                    <div className="mt-2 rounded-lg bg-neutral-50 border border-neutral-200 p-3 space-y-2">
                      {d.examples.map(ex => (
                        <div key={ex.score} className="flex gap-2 text-[11px]">
                          <span className="font-display font-bold text-ink w-4 shrink-0">{ex.score}</span>
                          <span className="text-muted leading-snug">
                            {lang === 'en' ? ex.en : ex.zh}
                          </span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Result */}
          <div className="lg:sticky lg:top-8 self-start">
            <div className="text-xs uppercase tracking-widest text-muted mb-3">Routing decision</div>
            <div className={`rounded-2xl border-2 p-6 ${TIER_COLOR[decision.tier]}`}>
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1 min-w-0">
                  <div className="font-display text-4xl mb-2">{tierLabel(decision.tier, lang)}</div>
                  <div className="text-sm leading-relaxed mb-4">{decision.reason}</div>
                  {decision.triggeredRules.length > 0 && (
                    <ul className="text-xs space-y-0.5">
                      {decision.triggeredRules.map(r => <li key={r}>• {r}</li>)}
                    </ul>
                  )}
                </div>
                <PentagonChart scoring={scoring} tier={decision.tier} lang={lang} />
              </div>
            </div>

            {/* Threshold hints */}
            {(() => {
              const hints = getThresholdHints(scoring, decision.tier, lang);
              if (hints.length === 0) return null;
              return (
                <div className="mt-3 space-y-1.5">
                  {hints.map((h, i) => {
                    const tierColors: Record<string, string> = {
                      'Tier-A': 'text-fuchsia-700 bg-fuchsia-50 border-fuchsia-200',
                      'Tier-Exec': 'text-emerald-700 bg-emerald-50 border-emerald-200',
                    };
                    const cls = tierColors[h.targetTier] ?? 'text-cyan-700 bg-cyan-50 border-cyan-200';
                    return (
                      <div key={i} className={`text-xs rounded-lg border px-3 py-2 ${cls}`}>
                        <span className="opacity-70">
                          {lang === 'en' ? `${h.targetTier} is 1 step away:` : `距 ${h.targetTier} 僅差：`}
                        </span>
                        {' '}
                        <span className="font-medium">↑ {h.changes.join(' · ')}</span>
                      </div>
                    );
                  })}
                </div>
              );
            })()}

            <div className="mt-6 flex flex-wrap gap-3">
              <button
                onClick={copyShareUrl}
                className="rounded-full px-6 py-3 text-sm border border-neutral-300 text-ink hover:bg-neutral-50 transition-colors"
              >
                {shareCopied ? '✓ Link copied' : 'Share this scoring'}
              </button>
              <button
                onClick={downloadHandoff}
                className="rounded-full px-6 py-3 text-sm bg-ink text-white hover:scale-[1.03] transition-transform"
              >
                Download handoff doc
              </button>
              <Link
                to="/doc/cli"
                className="rounded-full px-6 py-3 text-sm border border-neutral-300 text-ink hover:bg-neutral-50 transition-colors"
              >
                Use the CLI instead →
              </Link>
            </div>

            <div className="mt-8 text-xs text-muted leading-relaxed">
              <div className="font-medium text-ink mb-1">Routing rules</div>
              <code className="block bg-neutral-100 p-2 rounded text-[11px] font-mono whitespace-pre">
{`judgment≥4 OR risk≥4 OR creativity≥4 → Tier-A
judgment≤2 AND context≤2 AND verif≥4  → Tier-Exec
else                                  → Tier-Mid`}
              </code>
            </div>
          </div>
        </div>
      </div>

      {/* ── Prompt Builder ───────────────────────────────────────── */}
      <div className="max-w-6xl mx-auto px-5 sm:px-8 pb-16 pt-4">
        <div className="border-t border-neutral-200 pt-12">
          <div className="text-xs uppercase tracking-widest text-muted mb-2">Prompt Builder</div>
          <h2 className="font-display text-2xl sm:text-3xl text-ink mb-2">
            {lang === 'zh' ? '生成可直接使用的 Prompt' : 'Generate a ready-to-use prompt'}
          </h2>
          <p className="text-sm text-muted mb-8 max-w-2xl">
            {lang === 'zh'
              ? '選擇角色和工作模式，系統自動把任務描述 + 路由結果組合成一份結構化 prompt，可以直接貼進任何 AI 助手。'
              : 'Choose a role and flow. The system assembles your task + routing result into a structured prompt you can paste directly into any AI assistant.'}
          </p>

          {/* Step 1: Role */}
          <div className="mb-8">
            <div className="text-xs uppercase tracking-widest text-muted mb-3">
              {lang === 'zh' ? '步驟 1 — 選角色' : 'Step 1 — Choose a role'}
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2">
              {ROLES.map(r => (
                <button
                  key={r.id}
                  onClick={() => setSelectedRole(r.id)}
                  className={`rounded-xl border p-3 text-left transition-colors ${
                    selectedRole === r.id
                      ? 'border-ink bg-neutral-50'
                      : 'border-neutral-200 hover:border-neutral-400'
                  }`}
                >
                  <div className="text-xs font-medium text-ink mb-1">
                    {lang === 'zh' ? r.label : r.labelEn}
                  </div>
                  <div className="text-[10px] text-muted leading-snug">
                    {lang === 'zh' ? r.description : r.descriptionEn}
                  </div>
                  <div className="mt-2">
                    <span className={`text-[10px] px-1.5 py-0.5 rounded-full ${
                      r.tier === 'Tier-A' || r.tier === 'Tier-A/Mid' ? 'bg-fuchsia-100 text-fuchsia-700' :
                      r.tier === 'Tier-Exec' ? 'bg-emerald-100 text-emerald-700' :
                      'bg-cyan-100 text-cyan-700'
                    }`}>
                      {r.tier}
                    </span>
                  </div>
                </button>
              ))}
            </div>
          </div>

          {/* Step 2: Flow */}
          <div className="mb-8">
            <div className="text-xs uppercase tracking-widest text-muted mb-3">
              {lang === 'zh' ? '步驟 2 — 選工作模式' : 'Step 2 — Choose a flow'}
            </div>
            <div className="flex flex-wrap gap-2">
              {FLOWS.map(f => (
                <button
                  key={f.id}
                  onClick={() => setSelectedFlow(f.id)}
                  className={`rounded-full px-4 py-2 text-sm border transition-colors ${
                    selectedFlow === f.id
                      ? 'border-ink bg-ink text-white'
                      : 'border-neutral-300 hover:border-ink text-ink'
                  }`}
                >
                  {lang === 'zh' ? f.label : f.labelEn}
                  <span className="ml-2 text-[11px] opacity-60">
                    {lang === 'zh' ? f.description : f.descriptionEn}
                  </span>
                </button>
              ))}
            </div>
          </div>

          {/* Step 3: Generated Prompt */}
          <div>
            <div className="flex items-center justify-between mb-3">
              <div className="text-xs uppercase tracking-widest text-muted">
                {lang === 'zh' ? '步驟 3 — 你的 Prompt（複製後直接用）' : 'Step 3 — Your prompt (ready to paste)'}
              </div>
              <button
                onClick={async () => {
                  const prompt = buildPrompt(task, scoring, decision.tier, selectedRole, selectedFlow, lang);
                  try {
                    await navigator.clipboard.writeText(prompt);
                    setPromptCopied(true);
                    setTimeout(() => setPromptCopied(false), 1500);
                  } catch { /* clipboard unavailable */ }
                }}
                className="rounded-full px-4 py-1.5 text-xs border border-neutral-300 hover:border-ink transition-colors"
              >
                {promptCopied ? '✓ Copied' : (lang === 'zh' ? '複製 Prompt' : 'Copy prompt')}
              </button>
            </div>
            <pre className="bg-neutral-50 border border-neutral-200 rounded-xl p-5 text-xs font-mono leading-relaxed overflow-auto max-h-96 whitespace-pre-wrap">
              {buildPrompt(task, scoring, decision.tier, selectedRole, selectedFlow, lang)}
            </pre>
            <p className="mt-3 text-xs text-muted">
              {lang === 'zh'
                ? '💡 這是 System Prompt。配合「Download handoff doc」使用效果最好：handoff doc 作為 User 消息，這個作為 System 消息。'
                : '💡 This is your System Prompt. Pair it with the handoff doc for best results: handoff doc as the User message, this as the System message.'}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
